name: markpro_camera
description: "Professional Timestamp Camera for Proof of Work"
publish_to: 'none'
version: 1.0.10+11

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  gal: ^2.3.2
  http: ^1.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  share_plus: ^10.1.0
  image_picker: ^1.1.2
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  ota_update: ^7.0.1
  native_exif: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# Configuração do Ícone do App
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
